# Generated by Django 4.2.11 on 2024-06-29 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ",
                        editable=False,
                        length=8,
                        max_length=8,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("age_range", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ParentInfo",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ",
                        editable=False,
                        length=8,
                        max_length=8,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("city", models.CharField(max_length=32)),
                (
                    "feed_preferences",
                    models.JSONField(blank=True, default={}, null=True),
                ),
            ],
            options={
                "db_table": "parent_info",
                "get_latest_by": "modified",
            },
        ),
        migrations.CreateModel(
            name="ChildInfo",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ",
                        editable=False,
                        length=8,
                        max_length=8,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=32, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "MALE"),
                            ("FEMALE", "FEMALE"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("meta_info", models.JSONField(blank=True, default={}, null=True)),
                (
                    "parent_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_details",
                        to="parentune_task.parentinfo",
                    ),
                ),
            ],
            options={
                "db_table": "child_info",
                "get_latest_by": "modified",
            },
        ),
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ",
                        editable=False,
                        length=8,
                        max_length=8,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                ("content", models.TextField()),
                (
                    "suitable_for_gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suitable_for_age",
                    models.ManyToManyField(to="parentune_task.agegroup"),
                ),
            ],
            options={
                "db_table": "blogs",
                "get_latest_by": "modified",
            },
        ),
    ]
